name: Daily JSONSchema Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: {}

permissions:
  pull-requests: write
  contents: write

jobs:
  update-jsonschema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo $AWS_ACCESS_KEY_ID > aws-credentials
        echo $AWS_SECRET_ACCESS_KEY >> aws-credentials
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1

    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v2
      with:
        version: '1.7'
        force: 'true'

    - name: Run JSONSchema update script
      run: |
        jq --version
        chmod +x ./scripts/get_jsonschema.sh
        ./scripts/get_jsonschema.sh
        date -Isecond > ./data/date.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      id: create-pull-request
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        add-paths: |
          ./data/
        commit-message: Update addon data
        branch: auto/update-addon-data
        delete-branch: true
        branch-suffix: timestamp
        title: Update addon data

    - name: Enable Pull Request Automerge
      if: ${{ steps.create-pull-request.outputs.pull-request-number }}
      run: gh pr merge --squash --auto "${{ steps.create-pull-request.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
